language: node_js

node_js:
  - "8"
  - "10"
  - "12"

cache:
  yarn: true

env:
  - TARGET=wechat
  - TARGET=baidu
  - TARGET=alipay
  - TARGET=toutiao

install:
  - yarn install --frozen-lockfile
  - npx lerna bootstrap

script:
  - npx lerna run build
  - npx lerna run test
